name: SYSTEM_ROOT_AUTOMATION
on:
  workflow_dispatch:
    inputs:
      tema:
        description: 'Tema do post'
        required: true
        default: 'Cybersecurity'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Log
        run: echo "Disparado via Flutter para o tema ${{ github.event.inputs.tema }}"