name: SYSTEM_ROOT_AUTOMATION
on:
  workflow_dispatch:
    inputs:
      tema:
        description: 'Tema do post'
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Executar Script Python
        run: echo "Recebido tema: ${{ github.event.inputs.tema }}"
