name: SYSTEM_ROOT_AUTOMATION
on:
  workflow_dispatch:
    inputs:
      tema:
        description: 'Tema'
        required: true
jobs:
  executar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Log
        run: echo "Iniciando IA para o tema ${{ github.event.inputs.tema }}"
